<template>
    <ol>
        <li>beforeCreate</li>
        <li>created</li>
        <li>beforeMount</li>
        <li>mounted</li>
        <li>beforeUpdate</li>
        <li>updated</li>
        <li>beforeDestroy</li>
        <li>destroyed</li>
        <li>activated</li>
        <li>deactivated</li>
    </ol>
</template>
<script>
export default {
    beforeCreate(){
        console.log('beforeCreate')
    },
    created(){
        console.log('created')
    },
    beforeMount(){
        console.log('beforeMount')
    },
    mounted(){
        console.log('mounted')
    },
    beforeUpdate(){
        console.log('beforeUpdate')
    },
    updated(){
        console.log('updated')
    },
    beforeDestroy(){
        console.log('beforeDestroy')
    },
    destroyed(){
        console.log('destroyed')
    },
    activated(){
        console.log('activated')
    },
    deactivated(){
        console.log('deactivated')
    }
}
</script>